language: php

sudo: false

php:
    - 5.6
    - 7.0

install:
    - composer install --prefer-dist

script:
    - php vendor/bin/phpcs --standard=PSR2 Block/ Helper/ Model/ Observer/ Test/
    - php vendor/bin/phpmd Block/,Helper/,Model/,Observer/,Test/ text cleancode,codesize,controversial,design,naming,unusedcode
    - php vendor/bin/phpcpd Block/ Helper/ Model/ Observer/ Test/
    - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls